#%RAML 1.0 NamedExample
value: | 
  {
      "archivageDate": "2020-11-04T23:00:00.000Z",
      "createDate": "2020-11-04T23:00:00.000Z",
      "digestAlgo": "",
      "digestValueEncodedBase64": "",
      "docFileName": "anobdoc-C3",
      "docOwnerPublic": false,
      "docOwnerGroup": "",
      "docOwnerUser": "",
      "docTitle": "DOCUMENTS SORTANTS",
      "docType": "PDF",
      "gedId": 255,
      "overlayFormFileName": "",
      "storageType": "WORM",
      "uuid": "",
      "criterionList": [
          {
              "word": "1448470",
              "categoryId": 0
          },
          {
              "word": "20201105",
              "categoryId": 1
          },
          {
              "word": "280720477Y393370",
              "categoryId": 2
          },
          {
              "word": "280720477Y",
              "categoryId": 3
          },
          {
              "word": "393370",
              "categoryId": 4
          },
          {
              "word": "HUGUENIN",
              "categoryId": 5
          },
          {
              "word": "EMMANUEL",
              "categoryId": 6
          },
          {
              "word": "P",
              "categoryId": 8
          },
          {
              "word": "ALL_PAYMENTS",
              "categoryId": 12
          },
          {
              "word": "28720477Y101",
              "categoryId": 13
          },
          {
              "word": "S",
              "categoryId": 15
          },
          {
              "word": "COURRIER SORTANT",
              "categoryId": 17
          },
          {
              "word": "DECAISSEMENT SUITE AVENANT",
              "categoryId": 19
          },
          {
              "word": "0",
              "categoryId": 20
          },
          {
              "word": "0",
              "categoryId": 21
          },
          {
              "word": "PRESTATIONS",
              "categoryId": 35
          },
          {
              "word": "CLOTURE",
              "categoryId": 41
          }
      ]
  }