#%RAML 1.0 NamedExample
value: | 
  
  [
        {
            "score": -1,
            "documentExtended": {
                "wantedCriterionList": {
                    "criterionList": []
                },
                "docFileName": "group_22122020_180924_global.xml.481D89D.2.ged.SOR.378",
                "overlayFormFileName": "",
                "documentInformation": {
                    "lifeCycleRule": 0,
                    "numDoc": 1446,
                    "oldVersion": false,
                    "versionName": "",
                    "storageType": "WORM",
                    "createDate": "2020-12-21T23:00:00.000Z",
                    "gedId": 1446,
                    "docTitle": "DOCUMENTS SORTANTS",
                    "archivageDate": "2020-12-22T23:00:00.000Z",
                    "versionNumber": 1,
                    "docOwnerGroup": "",
                    "note": false,
                    "depositReceipt": false,
                    "overlayForm": false,
                    "uuid": "",
                    "docOwnerPublic": true,
                    "docOwnerUser": "",
                    "stampModif": 0,
                    "lifeCycleState": 0,
                    "lifeCycleIsLocked": false,
                    "annotation": false,
                    "documentSignature": false
                },
                "locked": false
            },
            "termFulltext": ""
      }
  ]
  
  
